plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/gabrielpaiva/Blueprint_Offensive/Outreach_Execution/deploy_ready_site/public"
publishOrigin = "ui"
commandOrigin = "ui"
command = "hugo"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]